package com.example.helloWorld;

// Generated by Selenium IDE
import static org.hamcrest.MatcherAssert.assertThat;
import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;

import java.util.*;

import org.junit.jupiter.api.extension.ExtendWith;
import io.github.bonigarcia.seljup.SeleniumJupiter;

@ExtendWith(SeleniumJupiter.class)
public class TesteAlineaCTest {
    private Map<String, Object> vars;
    JavascriptExecutor js;
    String driverPath = "/home/eva/Downloads/geckodriver-v0.30.0-linux64/geckodriver";
    public WebDriver firefoxDriver;

    
    @BeforeEach
    public void setUp() {
      vars = new HashMap<String, Object>();
      System.setProperty("webdriver.gecko.driver", driverPath);
      firefoxDriver = new FirefoxDriver();
    }

    @Test
    public void testeAlineaA() {
      js = (JavascriptExecutor) firefoxDriver;
      firefoxDriver.get("https://blazedemo.com/");
      firefoxDriver.manage().window().setSize(new Dimension(1848, 1053));
      firefoxDriver.findElement(By.cssSelector("h1")).click();
      vars.put("texth1", firefoxDriver.findElement(By.cssSelector("h1")).getText());
      assertEquals(vars.get("texth1").toString(), "Welcome to the Simple Travel Agency!");
      firefoxDriver.findElement(By.cssSelector(".btn-primary")).click();
      firefoxDriver.findElement(By.cssSelector("h3")).click();
      vars.put("texth3", firefoxDriver.findElement(By.cssSelector("h3")).getText());
      assertEquals(vars.get("texth3").toString(), "Flights from Paris to Buenos Aires:");
      firefoxDriver.findElement(By.cssSelector("tr:nth-child(1) .btn")).click();
      firefoxDriver.findElement(By.cssSelector("h2")).click();
      vars.put("texth2", firefoxDriver.findElement(By.cssSelector("h2")).getText());
      assertEquals(vars.get("texth2").toString(), "Your flight from TLV to SFO has been reserved.");
      firefoxDriver.findElement(By.id("inputName")).click();
      firefoxDriver.findElement(By.id("inputName")).sendKeys("Eva");
      firefoxDriver.findElement(By.id("address")).sendKeys("123 Main");
      firefoxDriver.findElement(By.id("city")).sendKeys("Aveiro");
      firefoxDriver.findElement(By.id("state")).sendKeys("Portugal");
      firefoxDriver.findElement(By.id("zipCode")).sendKeys("1234-567");
      firefoxDriver.findElement(By.id("creditCardNumber")).click();
      firefoxDriver.findElement(By.id("creditCardNumber")).click();
      firefoxDriver.findElement(By.id("creditCardNumber")).sendKeys("12345678");
      firefoxDriver.findElement(By.id("creditCardMonth")).click();
      firefoxDriver.findElement(By.id("creditCardMonth")).sendKeys("12");
      firefoxDriver.findElement(By.id("creditCardYear")).click();
      firefoxDriver.findElement(By.id("creditCardYear")).sendKeys("2018");
      firefoxDriver.findElement(By.id("nameOnCard")).click();
      firefoxDriver.findElement(By.id("nameOnCard")).sendKeys("Eva");
      firefoxDriver.findElement(By.cssSelector(".checkbox")).click();
      firefoxDriver.findElement(By.cssSelector(".btn-primary")).click();
      firefoxDriver.findElement(By.cssSelector("h1")).click();
      vars.put("texth1", firefoxDriver.findElement(By.cssSelector("h1")).getText());
      assertEquals(vars.get("texth1").toString(), "Thank you for your purchase today!");
      assertThat(firefoxDriver.getTitle(), is("BlazeDemo Confirmation"));
    }

    @AfterEach
    public void endTest() {
        firefoxDriver.quit();
    }
}
